project: 
  type: website
  
website: 
  page-navigation: true
  title: "RGovys Resources" 
  site-url: "https://rgovys.github.io/ResourceBook" 
  repo-url: https://github.com/Rgovys/ResourceBook
  repo-actions: [edit, issue]
  favicon: images/favicon.ico  
  
  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "This work is in the Public Domain [CC-1.0](https://creativecommons.org/publicdomain/zero/1.0/)"
  
  sidebar:
    background: "#D9E3E4"
    logo: "https://rgovys.github.io/images/Rgovys-logo.png"
    favicon: https://github.com/Rgovys/rgovys.github.io/blob/main/images/favicon_io/favicon-32x32.png?raw=true
    pinned: true
    align: center
    tools: 
      - icon: globe
        href: https://rgovys.github.io
        text: "RGovys"
      - icon: github
        href: https://github.com/rgovys
        text: "rgovys

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Home
      - href: content/welcome.qmd
        text: Welcome
      - href: content/code_of_conduct.qmd
      - href: content/culture.qmd
      - href: content/training.qmd
      - href: content/github_in_gov.qmd
      - href: content/R_in_gov.qmd
      - href: content/licenses_gov.qmd

format:
  html:
    theme:
      light: [cosmo, theme.scss] # from https://github.com/sta210-s22/website/blob/main/_quarto.yml
      dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    toc: true

filters:
  - include-files.lua
  - quarto

  
